# After changing this file, please run `make patch-upstream-helm` and regenerate the CRD
apiVersion: metal-stack.io/v1
kind: ClusterwideNetworkPolicy
metadata:
  name: xdr-proxy-access
  namespace: firewall
  labels:
    labels: {{- include "cortex-xdr.labels" . | nindent 4 }}
spec:
  egress:
  - toFQDNs:
    - matchName: registry.fits.cloud
    ports:
    - protocol: TCP
      port: 443
{{- if .Values.proxyAddresses }}
  {{- range .Values.proxyAddresses }}
  {{- $parts := split ":" . }}
  {{- if and $parts._0 $parts._1 }}
  - to:
    - cidr: {{ $parts._0 }}/32
    ports:
    - protocol: TCP
      port: {{ $parts._1 | int }}
  {{- end }}
  {{- end }}
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-egress-to-cortex-proxy
  namespace: {{ .Release.Namespace }}
spec:
  podSelector:
    matchLabels:
      app.kubernetes.io/name: cortex-xdr
  policyTypes:
  - Egress
  egress:
  {{- range .Values.proxyAddresses }}
  {{- $parts := split ":" . }}
  {{- if and $parts._0 $parts._1 }}
  - to:
    - ipBlock:
        cidr:{{ $parts._0 }}/32
    ports:
    - protocol: TCP
      port: {{ $parts._1 | int }}
  {{- end }}
  {{- end }}
{{- end }}

